### ISSUE TITLE
Preventing default click events

### ISSUE THREAD

**Issue by gbezyuk** [soundblogs/react-soundplayer#17]
Using provided PlayButton, NextButton etc. components, I end up being unable to prevent default click events, without hacking the lib's source code. So, if I, for instance, integrate the react-soundplayer in a form, any click is submitting it, which is not, by any means, a desirable behaviour.
From my perspective, it seems like react-soundplayer should run e.preventDefault() on any of it's controls.

**Comment by voronianski** [comment]
@gbezyuk I've published fix (https://github.com/soundblogs/react-soundplayer/commit/f5e884a50f910d9dcb9872f4edf0d4909ebb4d94) in `0.3.2`.
 
Few details:

- I'm not calling `e.preventDefault` directly but passing `event` instance to button handlers where it can be used. 
- also I've added `type="button"` to button tags in order to prevent unnecessary form submits.

**Comment by gbezyuk** [comment]
@voronianski great, thanx!
