### ISSUE TITLE
DEMO IS NOT WORKING. 

### ISSUE THREAD

**Issue by xih** [soundblogs/react-soundplayer#71]
https://labs.voronianski.com/react-soundplayer

![image](https://user-images.githubusercontent.com/8076886/28532329-ccf71664-7099-11e7-9865-5396f1c8b4bf.png)

**Comment by jamesdbruner** [comment]
Bump, but a different error now.

**Comment by voronianski** [comment]
@xih @jamesdbruner thanks, it's fine right now. 

However my soundcloud api client id is probably overused by someone else and there are no `remaining_requests` which means it's not possible to play the songs on the page. That sucks because it's quite hard to get new client id due to SoundCloud new policies.
